version: '3.9'

services:
  great_expectations:
    container_name: great_expectations
    build: .
    ports:
      - "8888:8888"
      - "8080:8080"
      - "8081:8081"
    tty: true
    working_dir: /usr/app
    environment:
      - DBT_PROFILES_DIR=/usr/app/dbt
      - AIRFLOW_HOME=/usr/app/dag
    volumes:
      - ./scr:/usr/app
      - gcloud-config:/root/.config
    secrets:
      - gcp_secret
  terraform:
    container_name: terraform
    entrypoint: ash
    image: hashicorp/terraform:latest
    working_dir: /tmp/terraform
    volumes:
      - ./scr/terraform:/tmp/terraform
      - gcloud-config:/root/.config
    tty: true
    secrets:
      - gcp_secret
  gcloud:
    container_name: gcloud
    entrypoint: "gcloud"
    image: google/cloud-sdk:alpine
    volumes:
      - gcloud-config:/root/.config
volumes:
  gcloud-config:
secrets:
  gcp_secret:
    file:
      ../secrets/gcp_secret_key_test_asasaki_data_owner.json