FROM python:3.9-slim

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y -q \
    git libpq-dev python3-dev build-essential supervisor && \
    apt-get install -y vim nano lsof curl &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install --upgrade pip && \
    pip install great_expectations sqlalchemy==1.4.25 sqlalchemy_bigquery pybigquery dbt-bigquery && \
    pip install apache-airflow[gcp] airflow-dbt

RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin

COPY ./dev/airflow.conf /etc/supervisor/conf.d/airflow.conf

CMD [ "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/airflow.conf" ]