dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /tmp/gcp_secret.json
      project: {project_id}
      dataset: asasaki_data_infra_dataset
      threads: 1
      timeout_seconds: 300
      location: us-central1 
      priority: interactive