steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/test-asasaki/prod_data_pipeline', '-f', './prod/Dockerfile.prod', '.' ]
  dir: .
images:
- 'gcr.io/test-asasaki/prod_data_pipeline'